import { PindanType } from '../../database/schemas/pindan.schema';

export const PINDAN_SEED: Array<{
  legacyId: number;
  type: PindanType;
  activityLegacyId: number;
  activityId: string;
  title: string;
  subtitle: string;
  image: string;
  price: number;
  originalPrice: number;
  date: string;
  location: string;
  joined: number;
  total: number;
  tags: string[];
  rating: number;
  includes?: Array<{ kind: 'hotel' | 'transport'; title: string; detail: string }>;
}> = [
  {
    legacyId: 1,
    type: 'package',
    activityLegacyId: 3,
    activityId: 's2o',
    title: '三亚电音节·全程套餐',
    subtitle: 'S2O Festival · 酒店+机票联合拼',
    image:
      'https://images.unsplash.com/photo-1540039155732-d674d4e3f421?w=400&q=80',
    price: 1580,
    originalPrice: 3800,
    date: '06/27-30',
    location: '三亚海棠湾',
    joined: 3,
    total: 4,
    tags: ['酒店+机票', '节省58%', '4晚住宿'],
    rating: 4.9,
    includes: [
      { kind: 'hotel', title: '亚特兰蒂斯海景房', detail: '3晚·含早餐' },
      { kind: 'transport', title: '上海→三亚 商务舱', detail: '06/27 PVG→SYX' },
    ],
  },
  {
    legacyId: 2,
    type: 'package',
    activityLegacyId: 2,
    activityId: 'edc',
    title: 'EDC China·出行套餐',
    subtitle: 'EDC China 2025 · 酒店+专车联合拼',
    image:
      'https://images.unsplash.com/photo-1470229722913-7c090be5c520?w=400&q=80',
    price: 980,
    originalPrice: 2280,
    date: '07/11-14',
    location: '苏州阳澄湖',
    joined: 2,
    total: 4,
    tags: ['酒店+专车', '节省57%', '3晚住宿'],
    rating: 4.8,
    includes: [
      { kind: 'hotel', title: '太湖精品湖景房', detail: '3晚·含双早' },
      { kind: 'transport', title: '上海→苏州 商务MPV', detail: '07/11 虹桥→阳澄湖' },
    ],
  },
  {
    legacyId: 3,
    type: 'package',
    activityLegacyId: 1,
    activityId: 'tomorrowland',
    title: 'Tomorrowland·周末套餐',
    subtitle: '预热派对 · 酒店+机票联合拼',
    image:
      'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=400&q=80',
    price: 1280,
    originalPrice: 2900,
    date: '06/19-21',
    location: '上海静安区',
    joined: 5,
    total: 6,
    tags: ['酒店+机票', '节省56%', '2晚住宿'],
    rating: 4.7,
    includes: [
      { kind: 'hotel', title: '外滩景观大床房', detail: '2晚·含早餐' },
      { kind: 'transport', title: '北京→上海 经济舱', detail: '06/19 PEK→PVG' },
    ],
  },
  {
    legacyId: 4,
    type: 'hotel',
    activityLegacyId: 3,
    activityId: 's2o',
    title: '三亚亚特兰蒂斯',
    subtitle: '海景大床房 · 4人均摊节省70%',
    image:
      'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=400&q=80',
    price: 450,
    originalPrice: 1800,
    date: '06/27-30',
    location: '三亚海棠湾',
    joined: 2,
    total: 4,
    tags: ['海景房', '含早餐'],
    rating: 4.9,
  },
  {
    legacyId: 5,
    type: 'hotel',
    activityLegacyId: 2,
    activityId: 'edc',
    title: '苏州太湖精品民宿',
    subtitle: '湖景套房 · 2人拼享8折',
    image:
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&q=80',
    price: 320,
    originalPrice: 640,
    date: '07/11-14',
    location: '苏州阳澄湖畔',
    joined: 1,
    total: 2,
    tags: ['湖景套房', '下午茶', '私人泳池'],
    rating: 4.8,
  },
  {
    legacyId: 6,
    type: 'hotel',
    activityLegacyId: 1,
    activityId: 'tomorrowland',
    title: '上海外滩威斯汀',
    subtitle: '外滩景观房 · 拼单立省60%',
    image:
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=400&q=80',
    price: 580,
    originalPrice: 1450,
    date: '06/19-21',
    location: '上海黄浦区',
    joined: 3,
    total: 4,
    tags: ['外滩景观', '含双早', '行政酒廊'],
    rating: 4.9,
  },
  {
    legacyId: 7,
    type: 'transport',
    activityLegacyId: 3,
    activityId: 's2o',
    title: '上海→三亚 商务舱拼',
    subtitle: '浦东机场出发 · 4座商务同行',
    image:
      'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=400&q=80',
    price: 1200,
    originalPrice: 4800,
    date: '06/27',
    location: 'PVG → SYX',
    joined: 2,
    total: 4,
    tags: ['商务舱', '行李直挂', '贵宾候机'],
    rating: 4.8,
  },
  {
    legacyId: 8,
    type: 'transport',
    activityLegacyId: 2,
    activityId: 'edc',
    title: '苏州活动专车',
    subtitle: '上海出发 · 7座商务MPV拼',
    image:
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80',
    price: 80,
    originalPrice: 560,
    date: '07/12',
    location: '上海虹桥 → 苏州阳澄湖',
    joined: 4,
    total: 7,
    tags: ['7座MPV', '司机接送', '准时准点'],
    rating: 4.9,
  },
  {
    legacyId: 9,
    type: 'transport',
    activityLegacyId: 3,
    activityId: 's2o',
    title: '三亚机场接驳拼',
    subtitle: '凤凰国际机场 → 海棠湾景区',
    image:
      'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=400&q=80',
    price: 40,
    originalPrice: 160,
    date: '06/27',
    location: '三亚凤凰机场',
    joined: 3,
    total: 4,
    tags: ['含行李', '准时接机', '空调车'],
    rating: 4.7,
  },
  {
    legacyId: 10,
    type: 'package',
    activityLegacyId: 4,
    activityId: 'ultra',
    title: 'Ultra Shanghai·全程套餐',
    subtitle: 'Ultra Shanghai · 酒店+机票联合拼',
    image:
      'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&q=80',
    price: 1680,
    originalPrice: 3600,
    date: '08/01-03',
    location: '上海世博公园',
    joined: 4,
    total: 6,
    tags: ['酒店+机票', '节省53%', '3晚住宿'],
    rating: 4.8,
    includes: [
      { kind: 'hotel', title: '浦东滨江景观房', detail: '3晚·含早餐' },
      { kind: 'transport', title: '广州→上海 商务舱', detail: '08/01 CAN→PVG' },
    ],
  },
  {
    legacyId: 11,
    type: 'hotel',
    activityLegacyId: 4,
    activityId: 'ultra',
    title: '世博公园周边精品酒店',
    subtitle: 'Ultra 专属 · 3晚连住拼房',
    image:
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=400&q=80',
    price: 480,
    originalPrice: 1200,
    date: '08/01-03',
    location: '上海浦东新区',
    joined: 2,
    total: 4,
    tags: ['近场馆', '含早餐', '延迟退房'],
    rating: 4.8,
  },
  {
    legacyId: 12,
    type: 'transport',
    activityLegacyId: 4,
    activityId: 'ultra',
    title: 'Ultra 接驳专线',
    subtitle: '上海各站点 → 世博公园',
    image:
      'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=400&q=80',
    price: 120,
    originalPrice: 360,
    date: '08/01-03',
    location: '上海各站点 → 世博公园',
    joined: 3,
    total: 5,
    tags: ['定点接驳', '含行李', '准时发车'],
    rating: 4.7,
  },
  {
    legacyId: 13,
    type: 'transport',
    activityLegacyId: 1,
    activityId: 'tomorrowland',
    title: '派对专车接送',
    subtitle: 'CLUB SPACE 往返 · 4座同行',
    image:
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80',
    price: 60,
    originalPrice: 240,
    date: '06/20',
    location: '上海市区 ↔ 静安区',
    joined: 2,
    total: 4,
    tags: ['夜间接送', '准时准点', '空调车'],
    rating: 4.6,
  },
  {
    legacyId: 14,
    type: 'package',
    activityLegacyId: 6,
    activityId: 'vac-zhuhai',
    title: 'VAC 珠海·希尔顿机酒套餐',
    subtitle: 'Vision & Colour · 3天2晚联合拼',
    image:
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&q=80',
    price: 1280,
    originalPrice: 3200,
    date: '04/18-19',
    location: '珠海',
    joined: 1,
    total: 4,
    tags: ['酒店+机票', '希尔顿', '3天2晚'],
    rating: 4.8,
    includes: [
      { kind: 'hotel', title: '珠海希尔顿海景房', detail: '2晚·含早餐' },
      { kind: 'transport', title: '往返机票拼', detail: '04/18 出发' },
    ],
  },
];
