export const ITINERARY_TOMORROWLAND_THAILAND_ACTIVITY_LEGACY_ID = 1;

const MAIN_STAGE = 'main' as const;

type TmlArtistSeed = {
  name: string;
  genre: string;
  genreLabel: string;
  popularity: number;
  genreColor: string;
};

function artistId(name: string): string {
  return name
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/&/g, 'and')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

/**
 * Tomorrowland Thailand 2026 全阵容官宣（Wisdom Valley · 12/11–13）。
 * `genre` 为主筛选项；`genreLabel` 为艺人实际代表曲风。
 * 官方演出时间表未发布前仅提供阵容预选，不写入占位排期。
 */
const TOMORROWLAND_THAILAND_ARTISTS: TmlArtistSeed[] = [
  {
    name: '22 BULLETS',
    genre: 'Hardstyle',
    genreLabel: 'Hardstyle · Euphoric',
    popularity: 82,
    genreColor: '#f97316',
  },
  {
    name: 'AFROJACK',
    genre: 'House',
    genreLabel: 'Big Room · Dutch House',
    popularity: 94,
    genreColor: '#f97316',
  },
  {
    name: 'AGENTS OF TIME',
    genre: 'Techno',
    genreLabel: 'Melodic Techno · Progressive',
    popularity: 86,
    genreColor: '#a855f7',
  },
  {
    name: 'ALAN WALKER',
    genre: 'House',
    genreLabel: 'Melodic House · EDM',
    popularity: 93,
    genreColor: '#38bdf8',
  },
  {
    name: 'ALOK',
    genre: 'House',
    genreLabel: 'Brazilian Bass · Slap House',
    popularity: 92,
    genreColor: '#22c55e',
  },
  {
    name: 'ALY & FILA',
    genre: 'Trance',
    genreLabel: 'Uplifting Trance · Egyptian',
    popularity: 88,
    genreColor: '#60a5fa',
  },
  {
    name: 'AMBER BROOS B2B SPACE 92',
    genre: 'Techno',
    genreLabel: 'Melodic Techno · Peak Time',
    popularity: 84,
    genreColor: '#c084fc',
  },
  {
    name: 'AMÉMÉ B2B HONEYLUV',
    genre: 'House',
    genreLabel: 'Afro House · Latin House',
    popularity: 83,
    genreColor: '#f472b6',
  },
  {
    name: 'AMY WILES',
    genre: 'House',
    genreLabel: 'Tech House · Melodic',
    popularity: 80,
    genreColor: '#34d399',
  },
  {
    name: 'AN!KA',
    genre: 'House',
    genreLabel: 'Tech House',
    popularity: 79,
    genreColor: '#e879f9',
  },
  {
    name: 'ANDROMEDIK',
    genre: 'Techno',
    genreLabel: 'Melodic Techno',
    popularity: 84,
    genreColor: '#818cf8',
  },
  {
    name: 'ANGEMI',
    genre: 'House',
    genreLabel: 'Big Room · Electro House',
    popularity: 85,
    genreColor: '#3b82f6',
  },
  {
    name: 'APASHE',
    genre: 'Bass',
    genreLabel: 'Bass · Dubstep · Orchestral',
    popularity: 87,
    genreColor: '#fb7185',
  },
  {
    name: 'ARTBAT',
    genre: 'Techno',
    genreLabel: 'Melodic Techno · Progressive',
    popularity: 90,
    genreColor: '#7c3aed',
  },
  {
    name: 'ARTBAT B2B R3HAB',
    genre: 'Techno',
    genreLabel: 'Melodic Techno · Big Room',
    popularity: 91,
    genreColor: '#6366f1',
  },
  {
    name: 'BASSJACKERS',
    genre: 'House',
    genreLabel: 'Big Room · Electro House',
    popularity: 89,
    genreColor: '#facc15',
  },
  {
    name: 'BIBI SECK',
    genre: 'House',
    genreLabel: 'Afro House · World',
    popularity: 80,
    genreColor: '#d97706',
  },
  {
    name: 'BLASTOYZ B2B WHITENO1SE',
    genre: 'Trance',
    genreLabel: 'Psytrance · Full-On',
    popularity: 85,
    genreColor: '#a3e635',
  },
  {
    name: 'BLAZY',
    genre: 'House',
    genreLabel: 'Tech House',
    popularity: 81,
    genreColor: '#4ade80',
  },
  {
    name: 'BOTCASH',
    genre: 'House',
    genreLabel: 'Tech House · Bass House',
    popularity: 80,
    genreColor: '#2dd4bf',
  },
  {
    name: 'BRENNAN HEART',
    genre: 'Hardstyle',
    genreLabel: 'Hardstyle · Euphoric',
    popularity: 89,
    genreColor: '#ea580c',
  },
  {
    name: 'CAMILA JUN',
    genre: 'House',
    genreLabel: 'Melodic House',
    popularity: 79,
    genreColor: '#f9a8d4',
  },
  {
    name: 'CAPOON',
    genre: 'Techno',
    genreLabel: 'Peak Time Techno',
    popularity: 83,
    genreColor: '#9333ea',
  },
  {
    name: 'CLAUDINE',
    genre: 'House',
    genreLabel: 'Tech House · Melodic',
    popularity: 80,
    genreColor: '#86efac',
  },
  {
    name: 'COSMIC GATE',
    genre: 'Trance',
    genreLabel: 'Progressive Trance · Trance',
    popularity: 90,
    genreColor: '#38bdf8',
  },
  {
    name: 'DA TWEEKAZ',
    genre: 'Hardstyle',
    genreLabel: 'Hardstyle · Raw',
    popularity: 88,
    genreColor: '#f97316',
  },
  {
    name: 'DADOO',
    genre: 'House',
    genreLabel: 'Tech House',
    popularity: 79,
    genreColor: '#6ee7b7',
  },
  {
    name: 'DENNIS GOLD',
    genre: 'House',
    genreLabel: 'Big Room · Electro',
    popularity: 82,
    genreColor: '#fbbf24',
  },
  {
    name: 'DIMITRI VEGAS & LIKE MIKE',
    genre: 'House',
    genreLabel: 'Big Room · Electro House',
    popularity: 97,
    genreColor: '#3b82f6',
  },
  {
    name: 'DINO LENNY',
    genre: 'House',
    genreLabel: 'Tech House · Acid',
    popularity: 84,
    genreColor: '#a78bfa',
  },
  {
    name: 'DJ SALLY',
    genre: 'House',
    genreLabel: 'Tech House · Melodic',
    popularity: 79,
    genreColor: '#f472b6',
  },
  {
    name: 'DJ TENNIS',
    genre: 'House',
    genreLabel: 'Tech House · Melodic',
    popularity: 86,
    genreColor: '#14b8a6',
  },
  {
    name: 'DUBVISION',
    genre: 'House',
    genreLabel: 'Progressive House · Big Room',
    popularity: 86,
    genreColor: '#60a5fa',
  },
  {
    name: 'DVBBS',
    genre: 'House',
    genreLabel: 'Big Room · Future Bass',
    popularity: 88,
    genreColor: '#22d3ee',
  },
  {
    name: 'ELFIGO',
    genre: 'House',
    genreLabel: 'Tech House',
    popularity: 80,
    genreColor: '#34d399',
  },
  {
    name: 'ELI & FUR B2B YOTTO',
    genre: 'House',
    genreLabel: 'Melodic House · Progressive',
    popularity: 87,
    genreColor: '#818cf8',
  },
  {
    name: 'FERRY CORSTEN',
    genre: 'Trance',
    genreLabel: 'Trance · Progressive Trance',
    popularity: 88,
    genreColor: '#0ea5e9',
  },
  {
    name: 'FIRAGA',
    genre: 'House',
    genreLabel: 'Tech House',
    popularity: 79,
    genreColor: '#4ade80',
  },
  {
    name: 'FLOSSTRADAMUS B2B YELLOW CLAW',
    genre: 'Bass',
    genreLabel: 'Trap · Bass Music',
    popularity: 88,
    genreColor: '#f43f5e',
  },
  {
    name: 'FUNK TRIBU',
    genre: 'Techno',
    genreLabel: 'Hard Techno · Acid',
    popularity: 86,
    genreColor: '#ef4444',
  },
  {
    name: 'GHOST RIDER',
    genre: 'Trance',
    genreLabel: 'Psytrance · Full-On',
    popularity: 84,
    genreColor: '#84cc16',
  },
  {
    name: 'GOLDFISH',
    genre: 'House',
    genreLabel: 'Live · Downtempo · Jazz',
    popularity: 83,
    genreColor: '#f59e0b',
  },
  {
    name: 'HALŌ',
    genre: 'House',
    genreLabel: 'Melodic House',
    popularity: 81,
    genreColor: '#c4b5fd',
  },
  {
    name: 'HALO',
    genre: 'House',
    genreLabel: 'Tech House · Melodic',
    popularity: 80,
    genreColor: '#a5b4fc',
  },
  {
    name: 'HANNAH LAING',
    genre: 'Techno',
    genreLabel: 'Hard Techno · Trance',
    popularity: 87,
    genreColor: '#f43f5e',
  },
  {
    name: 'HENRI BERGMANN',
    genre: 'Techno',
    genreLabel: 'Melodic Techno · Organic',
    popularity: 83,
    genreColor: '#8b5cf6',
  },
  {
    name: 'HENRI PFR',
    genre: 'House',
    genreLabel: 'Deep House · Melodic',
    popularity: 82,
    genreColor: '#2dd4bf',
  },
  {
    name: 'HONEY GEE',
    genre: 'House',
    genreLabel: 'Tech House',
    popularity: 79,
    genreColor: '#fcd34d',
  },
  {
    name: 'INFECTED MUSHROOM',
    genre: 'Trance',
    genreLabel: 'Psytrance · Progressive',
    popularity: 93,
    genreColor: '#a3e635',
  },
  {
    name: 'JAN V',
    genre: 'Techno',
    genreLabel: 'Peak Time Techno',
    popularity: 84,
    genreColor: '#7c3aed',
  },
  {
    name: 'JELLE DK',
    genre: 'Hardstyle',
    genreLabel: 'Hardstyle · Raw',
    popularity: 82,
    genreColor: '#fb923c',
  },
  {
    name: 'JERROOO',
    genre: 'House',
    genreLabel: 'Melodic House · Progressive',
    popularity: 85,
    genreColor: '#60a5fa',
  },
  {
    name: 'JOHN NEWMAN',
    genre: 'House',
    genreLabel: 'Pop · Vocal House',
    popularity: 87,
    genreColor: '#f472b6',
  },
  {
    name: 'JONNIE B',
    genre: 'House',
    genreLabel: 'Tech House',
    popularity: 79,
    genreColor: '#6ee7b7',
  },
  {
    name: 'KARTY',
    genre: 'House',
    genreLabel: 'Tech House · Bass House',
    popularity: 80,
    genreColor: '#34d399',
  },
  {
    name: 'KEVIN DE VRIES',
    genre: 'Techno',
    genreLabel: 'Melodic Techno · Peak Time',
    popularity: 88,
    genreColor: '#6366f1',
  },
  {
    name: 'KEVIN DE VRIES B2B MORTEN',
    genre: 'Techno',
    genreLabel: 'Melodic Techno · Big Room',
    popularity: 89,
    genreColor: '#4f46e5',
  },
  {
    name: 'KÖLSCH',
    genre: 'Techno',
    genreLabel: 'Melodic Techno · Organic',
    popularity: 90,
    genreColor: '#0d9488',
  },
  {
    name: 'LAIDBACK LUKE',
    genre: 'House',
    genreLabel: 'Electro House · Dutch House',
    popularity: 89,
    genreColor: '#facc15',
  },
  {
    name: 'LILLY PALMER',
    genre: 'Techno',
    genreLabel: 'Hard Techno · Peak Time',
    popularity: 87,
    genreColor: '#dc2626',
  },
  {
    name: 'LONSKII',
    genre: 'House',
    genreLabel: 'Tech House',
    popularity: 79,
    genreColor: '#4ade80',
  },
  {
    name: 'LOST FREQUENCIES',
    genre: 'House',
    genreLabel: 'Deep House · Tropical House',
    popularity: 90,
    genreColor: '#22d3ee',
  },
  {
    name: 'LUCAS & STEVE',
    genre: 'House',
    genreLabel: 'Future House · Big Room',
    popularity: 87,
    genreColor: '#ff2d55',
  },
  {
    name: 'LUUK VAN DIJK',
    genre: 'Techno',
    genreLabel: 'Tech House · Peak Time',
    popularity: 86,
    genreColor: '#9333ea',
  },
  {
    name: 'MAD MAXX B2B STRYKER',
    genre: 'Hardstyle',
    genreLabel: 'Hardstyle · Raw',
    popularity: 84,
    genreColor: '#ea580c',
  },
  {
    name: 'MANDY',
    genre: 'Techno',
    genreLabel: 'Melodic Techno',
    popularity: 83,
    genreColor: '#a855f7',
  },
  {
    name: 'MANUALS',
    genre: 'House',
    genreLabel: 'Tech House',
    popularity: 79,
    genreColor: '#2dd4bf',
  },
  {
    name: 'MARSH',
    genre: 'House',
    genreLabel: 'Melodic House · Progressive',
    popularity: 85,
    genreColor: '#818cf8',
  },
  {
    name: 'MARTIN GARRIX',
    genre: 'House',
    genreLabel: 'Big Room · Progressive House',
    popularity: 99,
    genreColor: '#ff2d55',
  },
  {
    name: 'MATISSE & SADKO',
    genre: 'House',
    genreLabel: 'Big Room · Progressive House',
    popularity: 86,
    genreColor: '#3b82f6',
  },
  {
    name: 'MATTN',
    genre: 'House',
    genreLabel: 'Big Room · Electro House',
    popularity: 84,
    genreColor: '#f97316',
  },
  {
    name: 'MAYSAA',
    genre: 'House',
    genreLabel: 'Melodic House',
    popularity: 79,
    genreColor: '#f9a8d4',
  },
  {
    name: 'MC STRETCH',
    genre: 'House',
    genreLabel: 'MC · Hip-Hop',
    popularity: 78,
    genreColor: '#a3a3a3',
  },
  {
    name: 'MEAGHAN',
    genre: 'House',
    genreLabel: 'Tech House · Melodic',
    popularity: 79,
    genreColor: '#e879f9',
  },
  {
    name: 'MEGURU',
    genre: 'House',
    genreLabel: 'Tech House',
    popularity: 79,
    genreColor: '#6ee7b7',
  },
  {
    name: 'MELTMODE',
    genre: 'Techno',
    genreLabel: 'Melodic Techno',
    popularity: 80,
    genreColor: '#8b5cf6',
  },
  {
    name: 'MEROW',
    genre: 'House',
    genreLabel: 'Tech House',
    popularity: 79,
    genreColor: '#34d399',
  },
  {
    name: 'MIKE BOND',
    genre: 'House',
    genreLabel: 'Big Room · Electro',
    popularity: 82,
    genreColor: '#fbbf24',
  },
  {
    name: 'MIND AGAINST',
    genre: 'Techno',
    genreLabel: 'Melodic Techno · Progressive',
    popularity: 90,
    genreColor: '#1e3a8a',
  },
  {
    name: 'NAKADIA',
    genre: 'Techno',
    genreLabel: 'Peak Time Techno · Acid',
    popularity: 86,
    genreColor: '#be185d',
  },
  {
    name: 'NERVO',
    genre: 'House',
    genreLabel: 'Progressive House · Electro House',
    popularity: 88,
    genreColor: '#ec4899',
  },
  {
    name: 'NETSKY',
    genre: 'Drum & Bass',
    genreLabel: 'Liquid D&B · Drum & Bass',
    popularity: 90,
    genreColor: '#22c55e',
  },
  {
    name: 'NICO MORENO',
    genre: 'Techno',
    genreLabel: 'Hard Techno · Peak Time',
    popularity: 85,
    genreColor: '#ef4444',
  },
  {
    name: 'NOME.',
    genre: 'Bass',
    genreLabel: 'Bass · Dubstep',
    popularity: 82,
    genreColor: '#fb7185',
  },
  {
    name: 'NOVAH',
    genre: 'House',
    genreLabel: 'Melodic House',
    popularity: 79,
    genreColor: '#c4b5fd',
  },
  {
    name: 'NUTTRIX',
    genre: 'Bass',
    genreLabel: 'Dubstep · Bass Music',
    popularity: 81,
    genreColor: '#f43f5e',
  },
  {
    name: 'OPPIDAN',
    genre: 'Drum & Bass',
    genreLabel: 'UK Bass · D&B',
    popularity: 84,
    genreColor: '#16a34a',
  },
  {
    name: 'PEGASSI',
    genre: 'House',
    genreLabel: 'Tech House',
    popularity: 80,
    genreColor: '#4ade80',
  },
  {
    name: 'PIXZY',
    genre: 'House',
    genreLabel: 'Tech House · Melodic',
    popularity: 79,
    genreColor: '#f472b6',
  },
  {
    name: 'PUFFER P',
    genre: 'House',
    genreLabel: 'Tech House',
    popularity: 79,
    genreColor: '#2dd4bf',
  },
  {
    name: 'QUINTINO',
    genre: 'House',
    genreLabel: 'Big Room · Electro House',
    popularity: 89,
    genreColor: '#facc15',
  },
  {
    name: 'R3HAB',
    genre: 'House',
    genreLabel: 'Big Room · Electro House',
    popularity: 91,
    genreColor: '#3b82f6',
  },
  {
    name: 'RAVE REPUBLIC',
    genre: 'Hardstyle',
    genreLabel: 'Hardstyle · Euphoric',
    popularity: 83,
    genreColor: '#f97316',
  },
  {
    name: 'RAYRAY',
    genre: 'House',
    genreLabel: 'Tech House · Bass House',
    popularity: 81,
    genreColor: '#34d399',
  },
  {
    name: 'RIVIERE',
    genre: 'House',
    genreLabel: 'Melodic House',
    popularity: 80,
    genreColor: '#818cf8',
  },
  {
    name: 'ROMEO BLANCO',
    genre: 'Trance',
    genreLabel: 'Trance · Uplifting',
    popularity: 84,
    genreColor: '#38bdf8',
  },
  {
    name: 'SABAI',
    genre: 'House',
    genreLabel: 'Future Bass · Melodic',
    popularity: 84,
    genreColor: '#22d3ee',
  },
  {
    name: 'SAINT LUDO',
    genre: 'House',
    genreLabel: 'Tech House · Melodic',
    popularity: 80,
    genreColor: '#a78bfa',
  },
  {
    name: 'SM1LE',
    genre: 'Hardstyle',
    genreLabel: 'Hardstyle · Raw',
    popularity: 82,
    genreColor: '#fb923c',
  },
  {
    name: 'STEVE AOKI',
    genre: 'House',
    genreLabel: 'Big Room · Electro House',
    popularity: 95,
    genreColor: '#ff2d55',
  },
  {
    name: 'SUB ZERO PROJECT',
    genre: 'Hardstyle',
    genreLabel: 'Hardstyle · Raw',
    popularity: 89,
    genreColor: '#dc2626',
  },
  {
    name: 'SWEDISH HOUSE MAFIA',
    genre: 'House',
    genreLabel: 'Progressive House · Big Room',
    popularity: 98,
    genreColor: '#facc15',
  },
  {
    name: 'THIRD PARTY',
    genre: 'House',
    genreLabel: 'Progressive House · Big Room',
    popularity: 87,
    genreColor: '#60a5fa',
  },
  {
    name: 'TIGER DRAMA',
    genre: 'House',
    genreLabel: 'Tech House',
    popularity: 79,
    genreColor: '#f97316',
  },
  {
    name: 'TRIPTICAL NOTE',
    genre: 'Techno',
    genreLabel: 'Melodic Techno',
    popularity: 79,
    genreColor: '#8b5cf6',
  },
  {
    name: 'VEGAS',
    genre: 'House',
    genreLabel: 'Big Room · Electro House',
    popularity: 85,
    genreColor: '#3b82f6',
  },
  {
    name: 'VINI VICI',
    genre: 'Trance',
    genreLabel: 'Psytrance · Progressive',
    popularity: 93,
    genreColor: '#a3e635',
  },
  {
    name: 'WHISNU SANTIKA',
    genre: 'House',
    genreLabel: 'Big Room · Indonesian EDM',
    popularity: 84,
    genreColor: '#f97316',
  },
  {
    name: 'WUKONG',
    genre: 'House',
    genreLabel: 'Big Room · Bass House',
    popularity: 83,
    genreColor: '#facc15',
  },
  {
    name: 'XCLUB.',
    genre: 'House',
    genreLabel: 'Tech House · Bass House',
    popularity: 81,
    genreColor: '#4ade80',
  },
  {
    name: 'XENIA DIA',
    genre: 'House',
    genreLabel: 'Melodic House',
    popularity: 80,
    genreColor: '#f9a8d4',
  },
  {
    name: 'XY',
    genre: 'Techno',
    genreLabel: 'Peak Time Techno',
    popularity: 82,
    genreColor: '#7c3aed',
  },
  {
    name: 'YELLOW CLAW',
    genre: 'Bass',
    genreLabel: 'Trap · Hardstyle',
    popularity: 88,
    genreColor: '#facc15',
  },
  {
    name: 'YOUNA',
    genre: 'Trance',
    genreLabel: 'Uplifting Trance · Hard Dance',
    popularity: 84,
    genreColor: '#ec4899',
  },
  {
    name: 'YUKIO',
    genre: 'House',
    genreLabel: 'Tech House',
    popularity: 79,
    genreColor: '#6ee7b7',
  },
  {
    name: 'YVES V',
    genre: 'House',
    genreLabel: 'Big Room · Electro House',
    popularity: 86,
    genreColor: '#3b82f6',
  },
];

const TML_DATE_META = [
  {
    dateKey: 'dec11',
    label: '12月11日',
    bannerDateLabel: '12月11日',
    sortOrder: 0,
  },
  {
    dateKey: 'dec12',
    label: '12月12日',
    bannerDateLabel: '12月12日',
    sortOrder: 1,
  },
  {
    dateKey: 'dec13',
    label: '12月13日',
    bannerDateLabel: '12月13日',
    sortOrder: 2,
  },
] as const;

export const TOMORROWLAND_THAILAND_FESTIVAL_SESSION_SEED = TML_DATE_META.map(
  (day) => ({
    activityLegacyId: ITINERARY_TOMORROWLAND_THAILAND_ACTIVITY_LEGACY_ID,
    ...day,
  }),
);

export const TOMORROWLAND_THAILAND_LINEUP_DJ_SEED =
  TOMORROWLAND_THAILAND_ARTISTS.map((artist) => {
    const id = artistId(artist.name);
    return {
      id,
      name: artist.name,
      genre: artist.genre,
      genreLabel: artist.genreLabel,
      stage: MAIN_STAGE,
      popularity: artist.popularity,
      avatarSeed: id,
      genreColor: artist.genreColor,
    };
  });

/** Lineup-only: official timetable not published yet. */
export const TOMORROWLAND_THAILAND_ARTIST_PERFORMANCE_SEED = [] as const;

export const TOMORROWLAND_THAILAND_ARTIST_NAMES =
  TOMORROWLAND_THAILAND_ARTISTS.map((artist) => artist.name);
