/** Demo posts aligned with frontend mock data (home, event detail, profile). */
export const POST_SEED = [
  {
    userId: 'demo-zara',
    authorName: 'Zara',
    authorHandle: '@zara_edm',
    authorAvatar:
      'https://images.unsplash.com/photo-1534751516642-a1af1ef26a56?w=120&q=80&fit=crop&crop=face',
    activityLegacyId: 1,
    eventTitle: 'Tomorrowland China',
    location: '上海',
    body: '7月18日上海场，求组队！有同城的小伙伴吗？可以一起拼住宿，已有2人，还差1个女生～',
    tags: ['#拼房', '#上海', '#女生优先'],
    status: 'recruiting',
    likes: 47,
    comments: 8,
    createdAt: new Date(Date.now() - 60_000),
  },
  {
    userId: 'demo-kyle',
    authorName: 'Kyle',
    authorHandle: '@kyle_beats',
    authorAvatar:
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&q=80&fit=crop&crop=face',
    activityLegacyId: 2,
    eventTitle: 'EDC China 2025',
    location: '北京',
    body: '北京站组队，3男1女，求最后一个小哥哥！已拼好套票+酒店，出发日期7月25日北京。',
    tags: ['#组队', '#北京', '#套票'],
    status: 'recruiting',
    likes: 31,
    comments: 6,
    createdAt: new Date(Date.now() - 32 * 60_000),
  },
  {
    userId: 'demo-nova',
    authorName: 'Nova',
    authorHandle: '@nova_rave',
    authorAvatar:
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&q=80&fit=crop&crop=face',
    activityLegacyId: 3,
    eventTitle: 'S2O 水上电音节',
    location: '成都',
    body: '成都S2O！求2个一起来的朋友，泼水节那天超爽！票我已经买好了，寻找同伴～',
    tags: ['#组队', '#成都'],
    status: 'recruiting',
    likes: 24,
    comments: 4,
    createdAt: new Date(Date.now() - 60 * 60_000),
  },
  {
    userId: 'demo-max',
    authorName: 'Max',
    authorHandle: '@max_underground',
    authorAvatar:
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=120&q=80&fit=crop&crop=face',
    activityLegacyId: 4,
    eventTitle: 'Boiler Room Shanghai',
    location: '上海',
    body: '周末场已成团，还可以一起现场集合，想认识同频朋友的可以来。',
    tags: ['#已成团', '#上海'],
    status: 'completed',
    likes: 18,
    comments: 3,
    createdAt: new Date(Date.now() - 2 * 60 * 60_000),
  },
  {
    userId: 'demo-zara',
    authorName: 'Zara',
    authorHandle: '@zara_edm',
    authorAvatar:
      'https://images.unsplash.com/photo-1534751516642-a1af1ef26a56?w=120&q=80&fit=crop&crop=face',
    activityLegacyId: 1,
    eventTitle: 'Tomorrowland China',
    location: '上海',
    body: '7月18日上海场，求组队！已有2人，还差1个女生～可以一起拼住宿，凌晨场一起出行！',
    tags: ['#拼房', '#上海', '#女生优先'],
    status: 'recruiting',
    likes: 47,
    comments: 2,
    createdAt: new Date(Date.now() - 90_000),
  },
  {
    userId: 'demo-iris',
    authorName: 'Iris',
    authorHandle: '@iris_edm',
    authorAvatar:
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&q=80&fit=crop&crop=face',
    activityLegacyId: 1,
    eventTitle: 'Tomorrowland China',
    location: '上海',
    body: '上海场找队友！已有2人，还差1个女生～可以一起拼住宿，凌晨场一起出行！',
    tags: ['#组队', '#凌晨场', '#上海场'],
    status: 'recruiting',
    likes: 18,
    comments: 5,
    createdAt: new Date(Date.now() - 3 * 60 * 60_000),
  },
  {
    userId: 'demo-wendy',
    authorName: 'Wendy',
    authorHandle: '@wendy_rave',
    authorAvatar:
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&q=80&fit=crop&crop=face',
    activityLegacyId: 1,
    eventTitle: 'Tomorrowland China',
    location: '上海',
    body: 'TMR上海！求最后一个拼房名额，女生优先，已有2人～',
    tags: ['#拼房', '#上海', '#女生'],
    status: 'recruiting',
    likes: 12,
    comments: 1,
    createdAt: new Date(Date.now() - 7 * 60 * 60_000),
  },
  {
    userId: 'demo-nova',
    authorName: 'Nova',
    authorHandle: '@nova_rave',
    authorAvatar:
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&q=80&fit=crop&crop=face',
    activityLegacyId: 2,
    eventTitle: 'EDC China 2025',
    location: '北京',
    body: 'EDC北京站！求2个一起来的朋友，票我已经买好了，寻找同伴～',
    tags: ['#组队', '#北京'],
    status: 'recruiting',
    likes: 24,
    comments: 3,
    createdAt: new Date(Date.now() - 2 * 60 * 60_000),
  },
  {
    userId: 'demo-zara',
    authorName: 'Zara',
    authorHandle: '@zara',
    authorAvatar:
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80',
    activityLegacyId: 3,
    eventTitle: 'S2O 水上电音节',
    location: '三亚',
    body: '成都S2O！求2个一起来的朋友，泼水节那天超爽！票我已经买好了，寻找同伴～',
    tags: [],
    status: 'completed',
    likes: 12,
    comments: 4,
    createdAt: new Date('2025-05-15'),
  },
  {
    userId: 'demo-zara',
    authorName: 'Zara',
    authorHandle: '@zara',
    authorAvatar:
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80',
    activityLegacyId: 2,
    eventTitle: 'EDC China 2025',
    location: '北京',
    body: '北京站组队，3男1女，求最后一个小哥哥！已拼好套票+酒店，出发日期7月25日。',
    tags: [],
    status: 'recruiting',
    likes: 31,
    comments: 6,
    createdAt: new Date('2025-04-28'),
  },
  {
    userId: 'demo-zara',
    authorName: 'Zara',
    authorHandle: '@zara',
    authorAvatar:
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80',
    activityLegacyId: 4,
    eventTitle: 'Boiler Room Shanghai',
    location: '上海',
    body: '周末场已成团，还可以一起现场集合，想认识同频朋友的可以来。',
    tags: [],
    status: 'completed',
    likes: 18,
    comments: 3,
    createdAt: new Date('2025-03-10'),
  },
];
