/** Demo posts aligned with 2026 festival catalog. */
export const POST_SEED = [
  {
    userId: 'demo-zara',
    authorName: 'Zara Chen',
    authorHandle: '@zara_edm',
    authorAvatar:
      'https://images.unsplash.com/photo-1534751516642-a1af1ef26a56?w=120&q=80&fit=crop&crop=face',
    activityLegacyId: 1,
    eventTitle: 'Tomorrowland Thailand 2026',
    location: '芭提雅',
    body:
      '12月芭提雅场求组队！想拼 Wisdom Valley 附近酒店，已有2人，还差1个女生～',
    tags: ['#住宿', '#芭提雅', '#女生优先'],
    status: 'recruiting',
    likes: 47,
    comments: 8,
    createdAt: new Date(Date.now() - 60_000),
  },
  {
    userId: 'demo-kyle',
    authorName: 'Kyle',
    authorHandle: '@kyle_beats',
    authorAvatar:
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&q=80&fit=crop&crop=face',
    activityLegacyId: 2,
    eventTitle: 'EDC China 2025',
    location: '苏州',
    body: '苏州阳澄湖场已结束，求同好分享现场攻略，明年还想再去！',
    tags: ['#组队', '#苏州', '#EDC'],
    status: 'recruiting',
    likes: 31,
    comments: 6,
    createdAt: new Date(Date.now() - 32 * 60_000),
  },
  {
    userId: 'demo-max',
    authorName: 'Max',
    authorHandle: '@max_underground',
    authorAvatar:
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=120&q=80&fit=crop&crop=face',
    activityLegacyId: 4,
    eventTitle: '风暴电音节 深圳站',
    location: '深圳',
    body: '6月13-14深圳国际会展中心，3缺1，已买好预售票，求一起进场的小伙伴！',
    tags: ['#STORM', '#深圳'],
    status: 'recruiting',
    likes: 18,
    comments: 3,
    createdAt: new Date(Date.now() - 2 * 60 * 60_000),
  },
  {
    userId: 'demo-zara',
    authorName: 'Zara Chen',
    authorHandle: '@zara_edm',
    authorAvatar:
      'https://images.unsplash.com/photo-1534751516642-a1af1ef26a56?w=120&q=80&fit=crop&crop=face',
    activityLegacyId: 1,
    eventTitle: 'Tomorrowland Thailand 2026',
    location: '芭提雅',
    body: 'TML泰国首站！求拼房+接机，已有2人，还差1个女生～',
    tags: ['#住宿', '#芭提雅', '#女生优先'],
    status: 'recruiting',
    likes: 47,
    comments: 2,
    createdAt: new Date(Date.now() - 90_000),
  },
  {
    userId: 'demo-iris',
    authorName: 'Iris',
    authorHandle: '@iris_edm',
    authorAvatar:
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&q=80&fit=crop&crop=face',
    activityLegacyId: 4,
    eventTitle: '风暴电音节 深圳站',
    location: '深圳',
    body: '深圳站组队！6月14日场，求2个一起来的 STORMer～',
    tags: ['#组队', '#深圳', '#STORM'],
    status: 'recruiting',
    likes: 18,
    comments: 5,
    createdAt: new Date(Date.now() - 3 * 60 * 60_000),
  },
  {
    userId: 'demo-wendy',
    authorName: 'Wendy',
    authorHandle: '@wendy_rave',
    authorAvatar:
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&q=80&fit=crop&crop=face',
    activityLegacyId: 5,
    eventTitle: 'EDC Thailand 2026',
    location: '普吉岛',
    body: '12月普吉岛 EDC，求最后一个住宿名额，女生优先～',
    tags: ['#住宿', '#普吉岛', '#女生'],
    status: 'recruiting',
    likes: 12,
    comments: 1,
    createdAt: new Date(Date.now() - 7 * 60 * 60_000),
  },
  {
    userId: 'demo-nova',
    authorName: 'Nova',
    authorHandle: '@nova_rave',
    authorAvatar:
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&q=80&fit=crop&crop=face',
    activityLegacyId: 5,
    eventTitle: 'EDC Thailand 2026',
    location: '普吉岛',
    body: 'EDC Thailand 12/18-20，Rhythm Park 见！求2个同行搭子～',
    tags: ['#组队', '#普吉岛'],
    status: 'recruiting',
    likes: 24,
    comments: 3,
    createdAt: new Date(Date.now() - 2 * 60 * 60_000),
  },
  {
    userId: 'demo-zara',
    authorName: 'Zara Chen',
    authorHandle: '@zara',
    authorAvatar:
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80',
    activityLegacyId: 4,
    eventTitle: '风暴电音节 深圳站',
    location: '深圳',
    body: '6月深圳 STORM 室内场首进，3男1女，求最后一个小哥哥！',
    tags: [],
    status: 'recruiting',
    likes: 31,
    comments: 6,
    createdAt: new Date('2026-05-20'),
  },
  {
    userId: 'demo-zara',
    authorName: 'Zara Chen',
    authorHandle: '@zara',
    authorAvatar:
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80',
    activityLegacyId: 6,
    eventTitle: '2026横琴VAC电音节',
    location: '珠海',
    body: '4月横琴 VAC 已组队，还可以一起现场集合，想认识同频朋友的可以来。',
    tags: [],
    status: 'completed',
    likes: 18,
    comments: 3,
    createdAt: new Date('2026-04-20'),
  },
];
