import type { TravelGuideBudgetTier } from '../domain/travel-guide.types';

export interface TravelGuideHotelSeedRow {
  activityLegacyId: number;
  budgetTier: TravelGuideBudgetTier;
  name: string;
  distanceLabel: string;
  distanceM: number;
  rating: number;
  pricePerNight: number;
  sortOrder: number;
}

/** 深圳国际会展中心（风暴 activityLegacyId=4）运营维护酒店清单 */
export const TRAVEL_GUIDE_HOTEL_SEED_ROWS: TravelGuideHotelSeedRow[] = [
  // 经济档 ¥150-300/晚
  {
    activityLegacyId: 4,
    budgetTier: 'economy',
    name: '深圳福华商务酒店(深圳国际会展中心店)',
    distanceLabel: '驾车2.6公里',
    distanceM: 2600,
    rating: 3.3,
    pricePerNight: 158,
    sortOrder: 1,
  },
  {
    activityLegacyId: 4,
    budgetTier: 'economy',
    name: '水岸国际公寓(深圳国际会展中心店)',
    distanceLabel: '驾车2.3公里',
    distanceM: 2300,
    rating: 4.7,
    pricePerNight: 224,
    sortOrder: 2,
  },
  {
    activityLegacyId: 4,
    budgetTier: 'economy',
    name: '铂京轻奢公寓(深圳国际会展中心店)',
    distanceLabel: '步行1.3公里',
    distanceM: 1300,
    rating: 4.4,
    pricePerNight: 194,
    sortOrder: 3,
  },
  {
    activityLegacyId: 4,
    budgetTier: 'economy',
    name: '豪吉丽娅公寓(深圳国际会展中心店)',
    distanceLabel: '驾车2.3公里',
    distanceM: 2300,
    rating: 4.7,
    pricePerNight: 269,
    sortOrder: 4,
  },
  {
    activityLegacyId: 4,
    budgetTier: 'economy',
    name: '鹏城酒店公寓(深圳国际会展中心店)',
    distanceLabel: '步行2公里',
    distanceM: 2000,
    rating: 4.6,
    pricePerNight: 247,
    sortOrder: 5,
  },
  {
    activityLegacyId: 4,
    budgetTier: 'economy',
    name: '富富优宿(深圳国际会展中心店)',
    distanceLabel: '驾车2.2公里',
    distanceM: 2200,
    rating: 4.4,
    pricePerNight: 279,
    sortOrder: 6,
  },
  // 舒适档 ¥300-600/晚
  {
    activityLegacyId: 4,
    budgetTier: 'standard',
    name: '铂京轻奢公寓(深圳国际会展中心店)',
    distanceLabel: '步行1.3公里',
    distanceM: 1300,
    rating: 4.4,
    pricePerNight: 319,
    sortOrder: 1,
  },
  {
    activityLegacyId: 4,
    budgetTier: 'standard',
    name: '黎曼国际公寓(深圳国际会展中心店)',
    distanceLabel: '步行1.4公里',
    distanceM: 1400,
    rating: 4.6,
    pricePerNight: 387,
    sortOrder: 2,
  },
  {
    activityLegacyId: 4,
    budgetTier: 'standard',
    name: '柏莱会展公寓(深圳国际会展中心华发冰雪世界店)',
    distanceLabel: '步行1.4公里',
    distanceM: 1400,
    rating: 4.5,
    pricePerNight: 387,
    sortOrder: 3,
  },
  {
    activityLegacyId: 4,
    budgetTier: 'standard',
    name: '铂睿行政公寓(深圳国际会展中心店)',
    distanceLabel: '步行1.3公里',
    distanceM: 1300,
    rating: 4.6,
    pricePerNight: 420,
    sortOrder: 4,
  },
  {
    activityLegacyId: 4,
    budgetTier: 'standard',
    name: '庭雅国际公寓(深圳华发冰雪世界店)',
    distanceLabel: '步行1.4公里',
    distanceM: 1400,
    rating: 4.8,
    pricePerNight: 456,
    sortOrder: 5,
  },
  {
    activityLegacyId: 4,
    budgetTier: 'standard',
    name: '柔居(深圳国际会展中心华发冰雪世界店)',
    distanceLabel: '步行1.3公里',
    distanceM: 1300,
    rating: 4.6,
    pricePerNight: 506,
    sortOrder: 6,
  },
  // 豪华档 ¥600+/晚
  {
    activityLegacyId: 4,
    budgetTier: 'comfort',
    name: '美豪酒店(深圳宝安国际会展中心华发冰雪世界店)',
    distanceLabel: '步行2公里',
    distanceM: 2000,
    rating: 4.7,
    pricePerNight: 613,
    sortOrder: 1,
  },
  {
    activityLegacyId: 4,
    budgetTier: 'comfort',
    name: '深圳国际会展中心希尔顿花园酒店(深圳前海华发冰雪世界店)',
    distanceLabel: '步行1.8公里',
    distanceM: 1800,
    rating: 4.7,
    pricePerNight: 649,
    sortOrder: 2,
  },
  {
    activityLegacyId: 4,
    budgetTier: 'comfort',
    name: '逸乐公寓(深圳市国际会展中心店)',
    distanceLabel: '驾车2.2公里',
    distanceM: 2200,
    rating: 4.7,
    pricePerNight: 666,
    sortOrder: 3,
  },
  {
    activityLegacyId: 4,
    budgetTier: 'comfort',
    name: '深圳国际会展中心洲际酒店',
    distanceLabel: '驾车2.3公里',
    distanceM: 2300,
    rating: 4.8,
    pricePerNight: 693,
    sortOrder: 4,
  },
  {
    activityLegacyId: 4,
    budgetTier: 'comfort',
    name: '房球通臻品公寓(深圳国际会展中心华发冰雪世界店)',
    distanceLabel: '步行1.6公里',
    distanceM: 1600,
    rating: 4.9,
    pricePerNight: 799,
    sortOrder: 5,
  },
  {
    activityLegacyId: 4,
    budgetTier: 'comfort',
    name: '深圳国际会展中心希尔顿酒店(前海华发冰雪世界店)',
    distanceLabel: '步行1.9公里',
    distanceM: 1900,
    rating: 4.8,
    pricePerNight: 799,
    sortOrder: 6,
  },
];
