/** Demo posts aligned with 2026 festival catalog. */
export const POST_SEED = [
  {
    userId: 'demo-zara',
    authorName: 'Zara Chen',
    authorHandle: '@zara_edm',
    authorAvatar:
      'https://images.unsplash.com/photo-1534751516642-a1af1ef26a56?w=120&q=80&fit=crop&crop=face',
    activityLegacyId: 1,
    eventTitle: 'Tomorrowland Thailand 2026',
    location: '芭提雅',
    body: '12月芭提雅场求组队！想拼 Wisdom Valley 附近酒店，已有2人，还差1个女生～',
    tags: ['#住宿', '#芭提雅', '#女生优先'],
    status: 'active',
    likes: 47,
    comments: 8,
    createdAt: new Date(Date.now() - 60_000),
  },
  {
    userId: 'demo-max',
    authorName: 'Max',
    authorHandle: '@max_underground',
    authorAvatar:
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=120&q=80&fit=crop&crop=face',
    activityLegacyId: 4,
    eventTitle: '风暴电音节 深圳站',
    location: '深圳',
    body: '6月13-14深圳国际会展中心，3缺1，已买好预售票，求一起进场的小伙伴！',
    tags: ['#STORM', '#深圳'],
    status: 'active',
    likes: 18,
    comments: 3,
    createdAt: new Date(Date.now() - 2 * 60 * 60_000),
  },
  {
    userId: 'demo-zara',
    authorName: 'Zara Chen',
    authorHandle: '@zara_edm',
    authorAvatar:
      'https://images.unsplash.com/photo-1534751516642-a1af1ef26a56?w=120&q=80&fit=crop&crop=face',
    activityLegacyId: 1,
    eventTitle: 'Tomorrowland Thailand 2026',
    location: '芭提雅',
    body: 'TML泰国首站！求拼房+接机，已有2人，还差1个女生～',
    tags: ['#住宿', '#芭提雅', '#女生优先'],
    status: 'active',
    likes: 47,
    comments: 2,
    createdAt: new Date(Date.now() - 90_000),
  },
  {
    userId: 'demo-iris',
    authorName: 'Iris',
    authorHandle: '@iris_edm',
    authorAvatar:
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&q=80&fit=crop&crop=face',
    activityLegacyId: 4,
    eventTitle: '风暴电音节 深圳站',
    location: '深圳',
    body: '深圳站组队！6月14日场，求2个一起来的 STORMer～',
    tags: ['#组队', '#深圳', '#STORM'],
    status: 'active',
    likes: 18,
    comments: 5,
    createdAt: new Date(Date.now() - 3 * 60 * 60_000),
  },
  {
    userId: 'demo-wendy',
    authorName: 'Wendy',
    authorHandle: '@wendy_rave',
    authorAvatar:
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&q=80&fit=crop&crop=face',
    activityLegacyId: 5,
    eventTitle: 'EDC Thailand 2026',
    location: '普吉岛',
    body: '12月普吉岛 EDC，求最后一个住宿名额，女生优先～',
    tags: ['#住宿', '#普吉岛', '#女生'],
    status: 'active',
    likes: 12,
    comments: 1,
    createdAt: new Date(Date.now() - 7 * 60 * 60_000),
  },
  {
    userId: 'demo-nova',
    authorName: 'Nova',
    authorHandle: '@nova_rave',
    authorAvatar:
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&q=80&fit=crop&crop=face',
    activityLegacyId: 5,
    eventTitle: 'EDC Thailand 2026',
    location: '普吉岛',
    body: 'EDC Thailand 12/18-20，Rhythm Park 见！求2个同行伙伴～',
    tags: ['#组队', '#普吉岛'],
    status: 'active',
    likes: 24,
    comments: 3,
    createdAt: new Date(Date.now() - 2 * 60 * 60_000),
  },
  {
    userId: 'demo-zara',
    authorName: 'Zara Chen',
    authorHandle: '@zara',
    authorAvatar:
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80',
    activityLegacyId: 4,
    eventTitle: '风暴电音节 深圳站',
    location: '深圳',
    body: '6月深圳 STORM 室内场首进，3男1女，求最后一个小哥哥！',
    tags: [],
    status: 'active',
    likes: 31,
    comments: 6,
    createdAt: new Date('2026-05-20'),
  },
];

/** 风暴电音节（legacyId=4）额外 demo 帖，用于 AI 发帖卡片展示测试 */
export const STORM_ACTIVITY_LEGACY_ID = 4;

export const STORM_DEMO_POST_SEED = [
  {
    userId: 'demo-luna',
    authorName: 'Luna',
    authorHandle: '@luna_storm',
    authorAvatar:
      'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=120&q=80&fit=crop&crop=face',
    activityLegacyId: STORM_ACTIVITY_LEGACY_ID,
    eventTitle: '风暴电音节 深圳站',
    location: '上海',
    departureCity: '上海',
    body: '6月13日场 13号A区 内场票已出，上海出发求同路到深圳，2人女生，可拼住宿～',
    tags: ['#13号A区', '#同路', '#拼住宿', '#女生优先'],
    status: 'active',
    likes: 52,
    comments: 9,
    createdAt: new Date(Date.now() - 45 * 60_000),
  },
  {
    userId: 'demo-sean',
    authorName: 'Sean',
    authorHandle: '@sean_storm',
    authorAvatar:
      'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&q=80&fit=crop&crop=face',
    activityLegacyId: STORM_ACTIVITY_LEGACY_ID,
    eventTitle: '风暴电音节 深圳站',
    location: '北京',
    departureCity: '北京',
    body: '北京出发深圳 STORM，从广州可同路接驳，今年 2 人求再拼 1 位同路人🚗',
    tags: ['#北京', '#同路', '#广州出发'],
    status: 'active',
    likes: 35,
    comments: 1,
    createdAt: new Date(Date.now() - 4 * 60 * 60_000),
  },
  {
    userId: 'demo-ryan',
    authorName: 'Ryan',
    authorHandle: '@ryan_edm',
    authorAvatar:
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&q=80&fit=crop&crop=face',
    activityLegacyId: STORM_ACTIVITY_LEGACY_ID,
    eventTitle: '风暴电音节 深圳站',
    location: '广州',
    departureCity: '广州',
    body: '风暴 STORM 深圳站 6月14日，B区看台，3缺1男生，广州同路出发，欢迎私信。',
    tags: ['#组队', '#B区', '#6月14日'],
    status: 'active',
    likes: 41,
    comments: 7,
    createdAt: new Date(Date.now() - 90 * 60_000),
  },
  {
    userId: 'demo-mia',
    authorName: 'Mia',
    authorHandle: '@mia_rave',
    authorAvatar:
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&q=80&fit=crop&crop=face',
    activityLegacyId: STORM_ACTIVITY_LEGACY_ID,
    eventTitle: '风暴电音节 深圳站',
    location: '深圳',
    departureCity: '深圳',
    body: '13号 A区 有没有人一起进场？本地土著带路，可分享检票口和接驳攻略，欢迎同行。',
    tags: ['#13号A区', '#组队', '#深圳'],
    status: 'active',
    likes: 36,
    comments: 11,
    createdAt: new Date(Date.now() - 3 * 60 * 60_000),
  },
  {
    userId: 'demo-alex',
    authorName: 'Alex',
    authorHandle: '@alex_underground',
    authorAvatar:
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=120&q=80&fit=crop&crop=face',
    activityLegacyId: STORM_ACTIVITY_LEGACY_ID,
    eventTitle: '风暴电音节 深圳站',
    location: '东莞',
    departureCity: '东莞',
    body: '6月13-14 连刷两场 STORM，已订会展中心附近酒店，求2人拼房，男生女生都可聊。',
    tags: ['#拼住宿', '#6月13日', '#6月14日'],
    status: 'active',
    likes: 28,
    comments: 4,
    createdAt: new Date(Date.now() - 5 * 60 * 60_000),
  },
  {
    userId: 'demo-sam',
    authorName: 'Sam',
    authorHandle: '@sam_beats',
    authorAvatar:
      'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&q=80&fit=crop&crop=face',
    activityLegacyId: STORM_ACTIVITY_LEGACY_ID,
    eventTitle: '风暴电音节 深圳站',
    location: '深圳',
    body: '13号A 区附近集合，预售票在手，缺1个会拍照的伙伴，主舞台前排区域～',
    tags: ['#13号A区', '#组队'],
    status: 'active',
    likes: 22,
    comments: 5,
    createdAt: new Date(Date.now() - 8 * 60 * 60_000),
  },
  {
    userId: 'demo-jade',
    authorName: 'Jade',
    authorHandle: '@jade_storm',
    authorAvatar:
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&q=80&fit=crop&crop=face',
    activityLegacyId: STORM_ACTIVITY_LEGACY_ID,
    eventTitle: '风暴电音节 深圳站',
    location: '杭州',
    departureCity: '杭州',
    body: '杭州飞深圳，6月13日风暴电音节，女生优先结伴，可AA拼酒店和打车，佛系不熬夜。',
    tags: ['#女生优先', '#拼住宿', '#6月13日'],
    status: 'active',
    likes: 19,
    comments: 3,
    createdAt: new Date(Date.now() - 12 * 60 * 60_000),
  },
  {
    userId: 'demo-leo',
    authorName: 'Leo',
    authorHandle: '@leo_edm',
    authorAvatar:
      'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=120&q=80&fit=crop&crop=face',
    activityLegacyId: STORM_ACTIVITY_LEGACY_ID,
    eventTitle: '风暴电音节 深圳站',
    location: '深圳',
    body: 'A区 6月13日场，2人组队缺1，已熟悉场馆动线，欢迎 STORMer 私聊结伴（平台内沟通即可）。',
    tags: ['#A区', '#6月13日', '#缺1人'],
    status: 'active',
    likes: 15,
    comments: 2,
    createdAt: new Date(Date.now() - 18 * 60 * 60_000),
  },
  {
    userId: 'demo-kai',
    authorName: 'Kai',
    authorHandle: '@kai_rave',
    authorAvatar:
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&q=80&fit=crop&crop=face',
    activityLegacyId: STORM_ACTIVITY_LEGACY_ID,
    eventTitle: '风暴电音节 深圳站',
    location: '北京',
    departureCity: '北京',
    body: '北京出发深圳 STORM，6月14日场，求同行伙伴一起看压轴，可同路可拼票区附近酒店。',
    tags: ['#同路', '#6月14日', '#组队'],
    status: 'active',
    likes: 14,
    comments: 1,
    createdAt: new Date(Date.now() - 24 * 60 * 60_000),
  },
  {
    userId: 'demo-nova-storm',
    authorName: 'Nova',
    authorHandle: '@nova_storm',
    authorAvatar:
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&q=80&fit=crop&crop=face',
    activityLegacyId: STORM_ACTIVITY_LEGACY_ID,
    eventTitle: '风暴电音节 深圳站',
    location: '深圳',
    body: '第一次来风暴电音节 13号场，想找人带一下换票区和储物柜流程，女生更好。',
    tags: ['#13号', '#新手友好', '#女生优先'],
    status: 'active',
    likes: 33,
    comments: 8,
    createdAt: new Date(Date.now() - 6 * 60 * 60_000),
  },
];
