/** 2026 电音节 catalog（来源：各 festival 官网 / 官方票务与文旅发布） */
export const ACTIVITY_SEED = [
  {
    legacyId: 1,
    code: 'tomorrowland',
    name: 'Tomorrowland Thailand 2026',
    alias: [
      'tomorrowland',
      'tomorrowland thailand',
      'tml泰国',
      '明日世界',
      'tmw',
    ],
    date: '12/11-13',
    location: '芭提雅 Wisdom Valley',
    latitude: 12.9367,
    longitude: 100.8839,
    region: 'overseas',
    image:
      'https://mma.prnewswire.com/media/2921955/Tomorrowland_Thailand_PR_Newswire.jpg',
    activityType: 'festival',
    hot: true,
  },
  {
    legacyId: 4,
    code: 'storm',
    name: '风暴电音节 深圳站',
    alias: ['storm', '风暴', '风暴电音节', '百威风暴', '口味王风暴'],
    date: '06/13-14',
    location: '深圳国际会展中心',
    latitude: 22.704518,
    longitude: 113.771513,
    region: 'domestic',
    image:
      'https://img.alicdn.com/imgextra/i2/2251059038/O1CN011VWlmX2GdSmiFVt13_!!2251059038.jpg',
    activityType: 'festival',
    hot: true,
    liveInfoZones: [
      { id: 'stage_a', label: 'A区' },
      { id: 'stage_b', label: 'B区' },
      { id: 'vip_booth', label: '卡座' },
      { id: 'venue', label: '全场' },
    ],
  },
  {
    legacyId: 5,
    code: 'edc-thailand',
    name: 'EDC Thailand 2026',
    alias: ['edc thailand', 'edc泰国', '泰国edc', 'edc 泰国'],
    date: '12/18-20',
    location: '普吉岛 Rhythm Park',
    latitude: 7.96,
    longitude: 98.35,
    region: 'overseas',
    image:
      'https://ik.imagekit.io/TBR/Island%20Events/EDC%20Thailand%202026.png?updatedAt=1763068886366',
    activityType: 'festival',
    hot: true,
  },
];
